#!/usr/bin/env bash

set -euo pipefail

dry_run="false"
hmBaseURL="https://github.com/rycee/home-manager/archive/"

source ./_lib

nixpksVersion() {
  echo "$nixpkgsVersion"
}

hmVersion() {
  echo "release-$(nixpksVersion)"
}

onDarwin() {
  uname -a | grep --quiet -i "darwin"
}

onNixOS() {
  false;
}

# install multi-user
function installNix() {
  if onDarwin; then
    ./install-nix-catalina.sh
  else
    _log "installing multi-user nix"
    _run "sh <(curl --location https://nixos.org/nix/install) --daemon"
  fi 
}

installNixDarwin() {
  if onDarwin; then
    _log "you're on a mac installing nix-darwin..."
    _run_optional "nix-build https://github.com/LnL7/nix-darwin/archive/master.tar.gz -A installer && ./result/bin/darwin-installer"
  fi
}

installHomeManager() {
  if onDarwin; then
    installNixDarwin
  elif onNixOS; then
    _log "On NixOS Skipping home-manager install..."
  else
    # Instructions from standalone installation from https://rycee.gitlab.io/home-manager/

    mkdir -m 0755 -p "/nix/var/nix/{profiles,gcroots}/per-user/$USER"
    nix-channel --add home-manager "${hmBaseURL}/$(hmVersion).tar.gz"
    nix-channel --update

    local shellExport="NIX_PATH=$HOME/.nix-defexpr/channels${NIX_PATH:+:}$NIX_PATH"

    $shellExport nix-shell '<home-manager>' -A install

    _log "Please add the following to your shell config:"
    _log "$shellExport"
  fi
}

installUserNixpkgs(){
  local nixpkgsDir="$HOME/.nixpkgs"

  if ! -d ./nixpkgs; then
    _error "YOu need to be in the same directory nixpkgs is located in. Did you (cd $HOME/dotfiles)?"
  fi

  if test -d $nixpkgsDir; then
    echo "$nixpkgsDir already exists! Backing it up first..."

    mv $nixpkgsDir "${nixpkgsDir}-backup"
  fi

  ln -sT ./nixpkgs $nixpkgsDir
}

rebuildHomeConfig() {
  _log "rebuilding home config"

  if onDarwin; then
    _run "darwin-rebuild switch"
  elif onNixOS; then
    _log "on NixOs skipping running home-manager rebuild...";
  else
    _run "home-manager switch"
  fi
  _log "depending on the config YOU MAY NEED TO RESTART THE MACHINE"
}

setFishShell() {
  if onDarwin; then
    _log "changing login shell for current user to the one generated by nix-darwin"
    chsh -s $(cat /etc/shells | grep "/run/current-system/" | grep "fish") $(whoami)
  else
    _log "Skipping setting login shell..."
  fi
}

installNix \
&& installHomeManager \
&& installUserNixpkgs \
&& rebuildHomeConfig \
&& setFishShell
